### ISSUE TITLE
Missing two functions

### ISSUE THREAD

**Issue by Gucci233** [kunzhan/SCDGN#1]
hello , I found two functions missing , cal_norm() and cal_Neg(). Please tell me where can I find them？

**Comment by kunzhan** [comment]
https://github.com/kunzhan/SCDGN/blob/main/dataset.py#L161

**Comment by kunzhan** [comment]
https://github.com/kunzhan/SCDGN/blob/main/dataset.py#L201

**Comment by Gucci233** [comment]
thank you
